# Generated by Django 3.2.1 on 2022-02-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbase',
            name='height',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbase',
            name='length',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productbase',
            name='width',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
