# Generated by Django 3.2.1 on 2022-02-13 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportallogo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_exportal_logo', to='product.exportalproduct'),
        ),
        migrations.AlterField(
            model_name='imageinternalmodel',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_internal', to='product.internalproduct'),
        ),
        migrations.AlterField(
            model_name='productbase',
            name='unique_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
