# Generated by Django 3.2.1 on 2022-02-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_loaded_transport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbase',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbase',
            name='loaded',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productbase',
            name='rejected',
            field=models.BooleanField(default=True),
        ),
    ]
